name: 'Custom Assembly'
on: [push, pull_request]
jobs:
  assembly:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Assemble
        run: |
          tar -a -c -f cambridge.zip libs load res scene tetris conf.lua main.lua scene.lua funcs.lua threaded_replay_code.lua
          rename cambridge.zip cambridge.love
          mkdir dist
          mkdir dist\windows
          mkdir dist\windows\libs
          mkdir dist\win32
          mkdir dist\win32\libs
          mkdir dist\other
          mkdir dist\other\libs

          copy /b dist\windows\love.exe+cambridge.love dist\windows\cambridge.exe
          copy /b dist\win32\love.exe+cambridge.love dist\win32\cambridge.exe
          copy /b cambridge.love dist\other\cambridge.love

          copy libs\discord-rpc.dll dist\windows\libs
          copy libs\discord-rpc.dll dist\win32\libs
          copy libs\discord-rpc.* dist\other\libs

          copy SOURCES.md dist\windows
          copy LICENSE.md dist\windows
          copy SOURCES.md dist\win32
          copy LICENSE.md dist\win32
          copy SOURCES.md dist\other
          copy LICENSE.md dist\other

          cd dist\windows
          tar -a -c -f ..\cambridge-windows.zip cambridge.exe *.dll libs *.md
          cd ..\..

          cd dist\win32
          tar -a -c -f ..\cambridge-win32.zip cambridge.exe *.dll libs *.md
          cd ..\..

          cd dist\other
          tar -a -c -f ..\cambridge-other.zip cambridge.love libs *.md
          cd ..\..
      - name: Upload Windows 32-bit artifact
        uses: actions/upload-artifact@v3
        with:
          name: cambridge_windows_x86
          path: dist/cambridge-win32.zip
      - name: Upload Windows 64-bit artifact
        uses: actions/upload-artifact@v3
        with:
          name: cambridge_windows_x64
          path: dist/cambridge-windows.zip
      - name: Upload other OS artifact
        uses: actions/upload-artifact@v3
        with:
          name: cambridge_other
          path: dist/cambridge-other.zip
      