name: 'Custom Assembly'
on: [push, pull_request]
jobs:
  assembly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Assemble
        run: |
          zip -r9 cambridge.love libs load res scene tetris conf.lua main.lua scene.lua funcs.lua threaded_replay_code.lua -x "res/img/rpc/*" res/bgm/pacer_test.mp3
          cat dist/windows/love.exe cambridge.love > dist/windows/cambridge.exe
          cat dist/win32/love.exe cambridge.love > dist/win32/cambridge.exe
          cp SOURCES.md LICENSE.md dist/windows/
          cp SOURCES.md LICENSE.md dist/win32/
          mkdir -vp dist/windows/libs/discordGameSDK/lib/x86_64/
          mkdir -vp dist/win32/libs/discordGameSDK/lib/x86/
          cp libs/discordGameSDK/lib/x86_64/discord_game_sdk.dll*  dist/windows/libs/discordGameSDK/lib/x86_64/
          cp libs/discordGameSDK/lib/x86/discord_game_sdk.* dist/win32/libs/discordGameSDK/lib/x86/
      - name: Upload Windows 32-bit artifact
        uses: actions/upload-artifact@v3
        with:
          name: cambridge_windows_x86
          path: |
            dist/win32/*
            !dist/win32/love.exe
      - name: Upload Windows 64-bit artifact
        uses: actions/upload-artifact@v3
        with:
          name: cambridge_windows_x64
          path: |
            dist/windows/*
            !dist/windows/love.exe
      - name: Upload other OS artifact
        uses: actions/upload-artifact@v3
        with:
          name: cambridge_other
          path: |
            cambridge.love
            libs/discordGameSDK/lib/x86_64/*
            SOURCES.md
            LICENSE.md
      - name: "Cleanup"
        run: |
          rm -f cambridge.love
          rm -f dist/windows/cambridge.exe
          rm -f dist/windows/SOURCES.md
          rm -f dist/windows/LICENSE.md
          rm -rf dist/windows/libs
          rm -f dist/win32/cambridge.exe
          rm -f dist/win32/SOURCES.md
          rm -f dist/win32/LICENSE.md
          rm -rf dist/win32/libs
      