name: 'Custom Assembly'
on: [push, pull_request]
jobs:
  assembly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Assemble
        run: |
          zip -r cambridge.love libs load res scene tetris conf.lua main.lua scene.lua funcs.lua threaded_replay_code.lua
          if [ ! -d "dist"]; then
            mkdir dist
          fi
          if [ ! -d "dist/windows"]; then
            mkdir dist/windows
          fi
          if [ ! -d "dist/win32"]; then
            mkdir dist/win32
          fi
          if [ ! -d "dist/other"]; then
            mkdir dist/other
          fi
          cat dist/windows/love.exe cambridge.love > dist/windows/cambridge.exe
          zip dist/cambridge-windows.zip dist/windows/* SOURCES.md LICENSE.md
          cat dist/win32/love.exe cambridge.love > dist/win32/cambridge.exe
          zip dist/cambridge-win32.zip dist/win32/* SOURCES.md LICENSE.md
          cp cambridge.love dist/other/
          zip dist/cambridge-other.zip cambridge.love libs/discord-rpc.* SOURCES.md LICENSE.md

      - name: Upload Windows 32-bit artifact
        uses: actions/upload-artifact@v3
        with:
          name: cambridge_windows_x86
          path: dist/cambridge-win32.zip
      - name: Upload Windows 64-bit artifact
        uses: actions/upload-artifact@v3
        with:
          name: cambridge_windows_x64
          path: dist/cambridge-windows.zip
      - name: Upload other OS artifact
        uses: actions/upload-artifact@v3
        with:
          name: cambridge_other
          path: dist/cambridge-other.zip
      - name: "Cleanup"
        run: |
          rm -f cambridge.love
          rm -f dist/windows/cambridge.exe
          rm -f dist/windows/SOURCES.md
          rm -f dist/windows/LICENSE.md
          if [-d "dist/windows/libs"]; then
            rm -r -f dist/windows/libs
          fi
          rm -f dist/win32/cambridge.exe
          rm -f dist/win32/SOURCES.md
          rm -f dist/win32/LICENSE.md
          if [-d "dist/win32/libs"]; then
            rm -r -f dist/win32/libs
          fi
          rm -f dist/other/cambridge.love
          rm -f dist/other/SOURCES.md
          rm -f dist/other/LICENSE.md
          if [-d "dist/other"]; then
            rm -r -f dist/other
          fi
          rm -f dist/cambridge-windows.zip
          rm -f dist/cambridge-win32.zip
          rm -f dist/cambridge-other.zip
      